apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: http
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - image: build_wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep php-fpm7'
          initialDelaySeconds: 15
          periodSeconds: 5
