apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer 
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 20
    targetPort: 20
    name: ftps-data
  - port: 21022
    targetPort: 21022
    name: ftps-passive
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: build_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 20
          name: ftps-data
        - containerPort: 21022
          name: ftps-passive
